# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd245fe25c1b2df2f859981eb9c74215eace581a379ae6cef4cafeacf0b8a03972f2329bedade73046756ddea1c16db15302779839b19e4a80a3cf9a4ef25599

test:
  secret_key_base: 06b0063f9ab7e8ed417963e2599f40367a4250db9b022ddf91bb76968b0a999b0d4be7d2bbb3eba9b7a7d9fa3f213d8b91983a9b7fe30deeaad2236a11b6c164

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
